name: Angular CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:

      - uses: actions/checkout@v4

      - name: Check Node
        shell: cmd
        run: |
          where node
          node -v
          npm -v

      - name: Install Packages
        run: npm install

      - name: Build Angular
        run: npm run build